### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by HerbFargus** [Omnija/herbomnijookelsaurus#1]
After some discussion with Rookervik we decided it may be prudent to rename the repo and relegate our awesome dinosaur name to our recently contrived mascot. 

So some rememberable name options might include:
- PortableGameStation
- USBGameStation
- RetroUSB
- RetroStick
- RetroPortable

Personally I'm partial to PortableGameStation as it seems to be the most ubiqitous (as this can be run on a portable harddrive, not just a USB) Retro may be slightly overused imo. 

I'm open to ideas.

![portable_game_station](https://cloud.githubusercontent.com/assets/10035308/12879730/808e6a4a-cdf5-11e5-865d-41ec4f97f09e.png)

![portable_game_station2](https://cloud.githubusercontent.com/assets/10035308/12879836/9f639804-cdf6-11e5-9403-12fbdf83c484.png)
#### MASCOT

![rookersaurus_2](https://cloud.githubusercontent.com/assets/10035308/12879637/622bfde4-cdf3-11e5-9ad4-c557d44c0773.png)

**Comment by Omnija** [comment]
P.R.E.S.C (Portable Retro Emulation Station Configurations)
